load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
  name = "keys",
  visibility = ["//visibility:public"],
  hdrs = ["keys.h"],
  srcs = ["keys.cpp"],
  deps = [
    "//third_party:opencv",
  ],
)
